id: P5A78D279
initial_creation_type: ocr
source_metadata:
  volumes:
    4f9058e17aaf4647aea7228a856b5601:
      base_file: v027.txt
      image_group_id: I1PD95872
      title: ཏིང་ངེ་འཛིན་གྱི་ཚོགས་ཀྱི་ལེའུ།
      total_pages: 1953
      volume_number: 27
